server:
  port: 8080

#nacos:
#  config:
#    bootstrap:
#      enable: true
#    server-addr: ${NACOS_SERVER:nacos.oneos-server.com:8848}
#    remote-first: true
#    data-ids: global-config.yaml,${spring.application.name}-${PROFILES_ACTIVE}.yaml
#    #data-ids: global-config.yaml,${spring.application.name}.dev.yaml
#    namespace: ${NACOS_NAMESPACE:3b70a32c-8fa6-4f77-961e-ba4d9518dbdb}
#    type: yaml
#    auto-refresh: true
#    username: ${NACOS_USERNAME:nacos}
#    password: ${NACOS_PASSWORD:nacos}

spring:
  application:
    name: lemon3
  #  profiles:
  #    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/testdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: "********"
    password: "********"
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    druid:
      filter:
        wall:
          config:
            none-base-statement-allow: true
            multi-statement-allow: true
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: "********"
        login-password: "********"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "********"
      database: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    client-id: lemon3
    consumer:
      group-id: lemon3-group
      max-poll-records: 10
      #Kafka中没有初始偏移或如果当前偏移在服务器上不再存在时,默认区最新 ，有三个选项 【latest, earliest, none】
      auto-offset-reset: earliest
      #是否开启自动提交
      enable-auto-commit: false
      #自动提交的时间间隔
      auto-commit-interval: 1000
    producer:
      acks: 1
      batch-size: 4096
      buffer-memory: 40960000
      client-id: lemon3
      compression-type: zstd
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.request.size: 126951500
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3  #推荐设置为topic的分区数
      type: BATCH #开启批量监听

  redis-cache:
    # 对引用的 key 设置过期时间
    keys-ttl:
      weatherCache: 10s


logging:
  level:
    root: INFO
    mybatis: DEBUG
    # 对指定的包开启日志级别
    com.leavis.lemon3.client: DEBUG

lemon:
  # 高德相关的配置
  amp:
    api-key: xxxxxxx  # 更换为实际的 key
    domain: https://restapi.amap.com
    read-time: 10000
    timeout: 10000
  kafka:
    consumer:
      topic: demo-topic