server:
  port: 8080
spring:
  application:
    name: lemon3
#  config:
#    import: nacos:global-config-${spring.profiles.active}.yaml,nacos:${spring.application.name}-${spring.profiles.active}.yaml
#  cloud:
#    nacos:
#      config:
#        server-addr: ${NACOS_SERVER:nacosserver:8848}
#        username: ${NACOS_USERNAME:nacos}
#        password: ${NACOS_PASSWORD:naocs}
#        namespace: ${NACOS_NAMESPACE:669e6433-2216-4695-a1cf-eefc05b99e6c}
#        file-extension: yaml
#        import-check:
#          enabled: false
#        refresh-enabled: true
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false  # 忽略空的属性
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/testdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: "********"
    password: "********"
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句
      validation-query: SELECT 1
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      filters: stat,wall,slf4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      filter:
        stat:
          enabled: true
          # 记录慢日志（"SQL监控"面板中数值会标记为红色）
          log-slow-sql: true
          # 慢日志判定标准（单位：毫秒）
          slow-sql-millis: 3000
          # 自定义日志级别，默认日志级别"ERROR"
          slow-sql-log-level: ERROR
        wall:
          config:
            none-base-statement-allow: true
            multi-statement-allow: true
      # 配置 DruidStatFilter
      web-stat-filter:
        # 启用"Web应用/URI监控/Session监控"面板
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        # 开启 ui 监控页面
        enabled: true
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        # deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: admin
        login-password: admin
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "********"
      database: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    client-id: lemon3
    consumer:
      group-id: lemon3-group
      max-poll-records: 10
      #Kafka中没有初始偏移或如果当前偏移在服务器上不再存在时,默认区最新 ，有三个选项 【latest, earliest, none】
      auto-offset-reset: earliest
      #是否开启自动提交
      enable-auto-commit: false
      #自动提交的时间间隔
      auto-commit-interval: 1000
    producer:
      acks: 1
      batch-size: 4096
      buffer-memory: 40960000
      client-id: lemon3
      compression-type: zstd
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.request.size: 126951500
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3  #推荐设置为topic的分区数
      type: BATCH #开启批量监听

  redis-cache:
    # 对引用的 key 设置过期时间
    keys-ttl:
      weatherCache: 10s
      ip2LocationCache: 100s

springdoc:
  api-docs:
    enabled: false # 关闭OpenApi接口
  swagger-ui:
    enabled: false # 关闭swagger界面

logging:
  level:
    root: INFO
    mybatis: DEBUG
    # 对指定的包开启日志级别
    com.leavis.lemon3.client: DEBUG

lemon:
  # 高德相关的配置
  amp:
    api-key: "********"  # 更换为实际的 key
    domain: https://restapi.amap.com
    read-time: 10000
    timeout: 10000
  kafka:
    consumer:
      topic: demo-topic
  netty:
    port: 8888
    heart-beat-timeout: 60
    ssl:
      enabled: false  # 是否开启ssl，todo开启ssl目前还有个bug未解决
      type: JKS
      key-store: ./lemon3.jks
      key-store-password: "********"