spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: password
  data:
    redis:
      host:  127.0.0.1
      port: 6379
      password: password
  kafka:
    bootstrap-servers: 127.0.0.1:9092
springdoc:
  api-docs:
    enabled: true # 个人开发打开OpenApi接口
  swagger-ui:
    enabled: true # 个人开发打开swagger界面
lemon:
  # 高德相关的配置
  amp:
    api-key: "********"  # 更换为实际的 key,在高德开放平台可以申请
  netty:
    ssl:
      key-store-password: "********"